# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Articulo.ipynb.

# %% auto 0
__all__ = ['Articulo']

# %% ../nbs/Articulo.ipynb 3
class Articulo:
    def __init__(self,
                 nombre:str,    #El nombre del artículo
                 cantidad:int): #La cantidad a comprar
        """
        Constructor de la clase Articulo.
        """
        self.nombre = nombre
        self.cantidad = cantidad
        self.agregado = False

    def marcar_como_agregado(self):
        """Marca el artículo como agregado."""
        self.agregado = True

